apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mother-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:michaelcampbell-spec/Mtn-lehlohonono.git'
    targetRevision: HEAD
    path: argo_git/workloads
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
