apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-nginx
  template:
    metadata:
      labels:
        app: first-nginx
    spec:
#      tolerations:
#        - key: "node-master/master"
#          operator: "Exists"
#          effect: "NoSchedule"
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: node-role.kubernetes.io/master
#                    operator: In
#                    values:
#                      - "true"
      containers:
        - name: first-nginx
          image: mec94/nginx-probable:latest
#          resources:
#           limits:
#              memory: "256Mi"
#              cpu: "1"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /file
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 6
            timeoutSeconds: 5
            failureThreshold: 2
