apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-workload
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.12
    helm:
      values: |
        grafana.ini:
          smtp:
            enabled: true
            host: "smtp.gmail.com:587"
            user: "michael.campbell@lsdopen.io"
            password: "wsnuhfgupskkklgk "
            from_address: "michael.campbell@lsdopen.io"
            from_name: "AKS Grafana Alerts"
      parameters:
        - name: service.type
          value: ClusterIP
        - name: assertNoLeakedSecrets
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
