apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-workload
  namespace: argocd
spec:
  project: default
  source:
    # 1. Point Argo CD directly to the official Grafana Helm Web Registry
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 8.5.x
    helm:
      parameters:
        - name: service.type
          value: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
