apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-workload
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:michaelcampbell-spec/Mtn-lehlohonono.git'
    targetRevision: HEAD
    path: workloads/nginx
  destination:
    server: 'https://default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
