apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-workload
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.io'
    chart: prometheus
    targetRevision: 26.x.x
    helm:
      parameters:
        - name: alertmanager.enabled
          value: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
