apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: official-grafana-release
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://github.io
    targetRevision: 8.5.x
    helm:
      parameters:
        - name: service.type
          value: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
